services:
  postgres:
    image: postgres:16
    container_name: s2o_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: s2o
    ports:
      - "5432:5432"
    volumes:
      - s2o_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: s2o_redis
    ports:
      - "6379:6379"

volumes:
  s2o_pg:
