version: "3.9"

services:
  api-gateway:
    build: ./src/ApiGateway
    ports:
      - "8000:8080"
    depends_on:
      - identity-service
      - tenant-service

  identity-service:
    image: identity-service
    container_name: identity-service
    ports:
      - "5001:5000"

  tenant-service:
    image: tenant-service
    container_name: tenant-service
    ports:
      - "5002:5000"
